#include "Weird.h"
#include <iostream>

#define _MESSAGE "Cursed C++"

__VOID Log LEFT_PARAN __CONST __CHAR* message RIGHT_PARAN SEMI_COLON

__INT __MAIN_CALL LEFT_PARAN RIGHT_PARAN
LEFT_CURLY
	Log LEFT_PARAN _MESSAGE RIGHT_PARAN SEMI_COLON
	__STANDARD_LIB __DBL_COLON __CIN DOT __GET_FUNC SEMI_COLON
RIGHT_CURLY

__VOID Log LEFT_PARAN __CONST __CHAR* message RIGHT_PARAN
LEFT_CURLY
	__STANDARD_LIB __DBL_COLON __COUT __DBL_LEFT_AGL message __DBL_LEFT_AGL __STANDARD_LIB __DBL_COLON __ENDL SEMI_COLON
RIGHT_CURLY



